import type { Product, ProductSpec } from "@/types/product";
import type { SiteSettings } from "@/types/site-settings";

const PLACEHOLDER_IMAGE = "/placeholders/product-default.svg";
const NOW = new Date().toISOString();

function buildSpecs(
  productId: string,
  specs: Array<{ key: string; value: string }>,
): ProductSpec[] {
  return specs.map((spec, index) => ({
    id: `${productId}-spec-${index + 1}`,
    productId,
    key: spec.key,
    value: spec.value,
    sortOrder: index + 1,
  }));
}

function buildProduct(product: Omit<Product, "images" | "specs" | "createdAt" | "updatedAt"> & {
  imageAlt: string;
  specs: Array<{ key: string; value: string }>;
}): Product {
  return {
    ...product,
    createdAt: NOW,
    updatedAt: NOW,
    images: [
      {
        id: `${product.id}-img-1`,
        productId: product.id,
        url: PLACEHOLDER_IMAGE,
        alt: product.imageAlt,
        sortOrder: 1,
      },
    ],
    specs: buildSpecs(product.id, product.specs),
  };
}

export const mockSiteSettings: SiteSettings = {
  heroHeadline: "Precision in Time & Vision",
  heroSubheadline:
    "Ora te kuruara, syze te rafinuara dhe servis i besuar ne Gjilan.",
  heroPrimaryCtaLabel: "Shop Watches",
  heroPrimaryCtaHref: "/watches",
  heroSecondaryCtaLabel: "Request Repair",
  heroSecondaryCtaHref: "/service/request",
  trustPoints: [
    "Dyqan fizik ne qender te Gjilanit",
    "Servis real per ore dhe syze",
    "Perzgjedhje e kuruar e modeleve",
    "Dergese lokale dhe terheqje ne dyqan",
  ],
  serviceHighlights: [
    "Ndrrim baterie",
    "Ndrrim rripi dhe rregullim byzylyku",
    "Diagnostikim i mekanizmit",
    "Rregullim dhe pershtatje e syzeve",
  ],
  storeAddress: "Rruga e Qytetit, Gjilan 60000, Kosovo",
  storeHours: "Hene - Shtune, 09:00 - 19:00",
  storePhone: "+383 44 000 000",
  storeWhatsapp: "+383 44 000 000",
  mapUrl:
    "https://www.google.com/maps/search/?api=1&query=Gjilan+Kosovo",
};

export const mockProducts: Product[] = [
  buildProduct({
    id: "w-001",
    slug: "seiko-presage-srpb41",
    title: "Presage SRPB41",
    brand: "Seiko",
    category: "watch",
    subtype: "analog_watch",
    shortDescription: "Classic automatic dress watch with deep blue dial.",
    description:
      "A balanced automatic model with elegant proportions for daily and formal wear.",
    price: 469,
    currency: "EUR",
    stockStatus: "in_stock",
    quantity: 5,
    featured: true,
    isNew: true,
    status: "active",
    primaryCtaMode: "add_to_cart",
    imageAlt: "Seiko Presage SRPB41 on warm ivory background",
    specs: [
      { key: "movement", value: "Automatic" },
      { key: "strap", value: "Leather" },
      { key: "dial_color", value: "Blue" },
      { key: "case_size", value: "40.5mm" },
      { key: "water_resistance", value: "50m" },
    ],
  }),
  buildProduct({
    id: "w-002",
    slug: "tissot-prx-quartz-40",
    title: "PRX Quartz 40",
    brand: "Tissot",
    category: "watch",
    subtype: "analog_watch",
    shortDescription: "Integrated bracelet icon with precise quartz movement.",
    description:
      "A modern classic with clean geometry and strong everyday wear resistance.",
    price: 395,
    currency: "EUR",
    stockStatus: "in_stock",
    quantity: 4,
    featured: true,
    isNew: false,
    status: "active",
    primaryCtaMode: "add_to_cart",
    imageAlt: "Tissot PRX quartz with steel bracelet",
    specs: [
      { key: "movement", value: "Quartz" },
      { key: "strap", value: "Bracelet" },
      { key: "dial_color", value: "Silver" },
      { key: "case_size", value: "40mm" },
      { key: "water_resistance", value: "100m" },
    ],
  }),
  buildProduct({
    id: "w-003",
    slug: "citizen-eco-drive-bm7108",
    title: "Eco-Drive BM7108",
    brand: "Citizen",
    category: "watch",
    subtype: "analog_watch",
    shortDescription: "Solar-powered precision with understated styling.",
    description:
      "A clean watch powered by light, built for low maintenance and reliable timekeeping.",
    price: 289,
    currency: "EUR",
    stockStatus: "limited",
    quantity: 2,
    featured: true,
    isNew: false,
    status: "active",
    primaryCtaMode: "add_to_cart",
    imageAlt: "Citizen eco-drive watch closeup",
    specs: [
      { key: "movement", value: "Eco-Drive" },
      { key: "strap", value: "Leather" },
      { key: "dial_color", value: "White" },
      { key: "case_size", value: "41mm" },
      { key: "water_resistance", value: "100m" },
    ],
  }),
  buildProduct({
    id: "w-004",
    slug: "orient-bambino-v7",
    title: "Bambino V7",
    brand: "Orient",
    category: "watch",
    subtype: "analog_watch",
    shortDescription: "Refined automatic dress watch with domed crystal.",
    description:
      "A classic profile for formal settings with dependable in-house automatic movement.",
    price: 259,
    currency: "EUR",
    stockStatus: "in_stock",
    quantity: 6,
    featured: false,
    isNew: false,
    status: "active",
    primaryCtaMode: "add_to_cart",
    imageAlt: "Orient Bambino model on leather strap",
    specs: [
      { key: "movement", value: "Automatic" },
      { key: "strap", value: "Leather" },
      { key: "dial_color", value: "Cream" },
      { key: "case_size", value: "40mm" },
      { key: "water_resistance", value: "30m" },
    ],
  }),
  buildProduct({
    id: "w-005",
    slug: "casio-edifice-efv-100",
    title: "Edifice EFV-100",
    brand: "Casio",
    category: "watch",
    subtype: "analog_watch",
    shortDescription: "Sporty quartz watch with clean chronograph-inspired profile.",
    description:
      "A practical everyday watch focused on legibility, comfort, and reliability.",
    price: 129,
    currency: "EUR",
    stockStatus: "in_stock",
    quantity: 8,
    featured: false,
    isNew: true,
    status: "active",
    primaryCtaMode: "add_to_cart",
    imageAlt: "Casio Edifice watch product profile",
    specs: [
      { key: "movement", value: "Quartz" },
      { key: "strap", value: "Bracelet" },
      { key: "dial_color", value: "Black" },
      { key: "case_size", value: "42mm" },
      { key: "water_resistance", value: "100m" },
    ],
  }),
  buildProduct({
    id: "w-006",
    slug: "hamilton-khaki-field-auto",
    title: "Khaki Field Auto",
    brand: "Hamilton",
    category: "watch",
    subtype: "analog_watch",
    shortDescription: "Field watch design with Swiss automatic movement.",
    description:
      "A robust yet refined model with strong legibility and day-to-day versatility.",
    price: 739,
    currency: "EUR",
    stockStatus: "available_on_request",
    quantity: null,
    featured: true,
    isNew: false,
    status: "active",
    primaryCtaMode: "request_availability",
    imageAlt: "Hamilton Khaki Field automatic watch",
    specs: [
      { key: "movement", value: "Automatic" },
      { key: "strap", value: "Textile" },
      { key: "dial_color", value: "Green" },
      { key: "case_size", value: "38mm" },
      { key: "water_resistance", value: "100m" },
    ],
  }),
  buildProduct({
    id: "w-007",
    slug: "longines-conquest-39",
    title: "Conquest 39",
    brand: "Longines",
    category: "watch",
    subtype: "analog_watch",
    shortDescription: "Premium Swiss profile for modern daily wear.",
    description:
      "A contemporary sports-luxury silhouette with high finishing and precise movement.",
    price: 1640,
    currency: "EUR",
    stockStatus: "available_on_request",
    quantity: null,
    featured: true,
    isNew: false,
    status: "active",
    primaryCtaMode: "whatsapp_inquiry",
    imageAlt: "Longines Conquest watch campaign view",
    specs: [
      { key: "movement", value: "Automatic" },
      { key: "strap", value: "Bracelet" },
      { key: "dial_color", value: "Blue" },
      { key: "case_size", value: "39mm" },
      { key: "water_resistance", value: "100m" },
    ],
  }),
  buildProduct({
    id: "w-008",
    slug: "mondaine-classic-36",
    title: "Classic 36",
    brand: "Mondaine",
    category: "watch",
    subtype: "analog_watch",
    shortDescription: "Minimal Swiss-inspired dial with clean everyday lines.",
    description:
      "A design-driven model for understated style with dependable quartz precision.",
    price: 229,
    currency: "EUR",
    stockStatus: "in_stock",
    quantity: 3,
    featured: false,
    isNew: false,
    status: "active",
    primaryCtaMode: "add_to_cart",
    imageAlt: "Mondaine classic watch with white dial",
    specs: [
      { key: "movement", value: "Quartz" },
      { key: "strap", value: "Leather" },
      { key: "dial_color", value: "White" },
      { key: "case_size", value: "36mm" },
      { key: "water_resistance", value: "30m" },
    ],
  }),
  buildProduct({
    id: "e-001",
    slug: "ray-ban-rx7140",
    title: "RX7140",
    brand: "Ray-Ban",
    category: "eyewear",
    subtype: "frame",
    shortDescription: "Lightweight optical frame with modern square profile.",
    description:
      "A clean silhouette for daily wear with strong comfort and versatile fit.",
    price: 169,
    currency: "EUR",
    stockStatus: "in_stock",
    quantity: 7,
    featured: true,
    isNew: true,
    status: "active",
    primaryCtaMode: "add_to_cart",
    imageAlt: "Ray-Ban optical frame product shot",
    specs: [
      { key: "frame_type", value: "Frames" },
      { key: "shape", value: "Square" },
      { key: "material", value: "Acetate" },
      { key: "color", value: "Black" },
      { key: "gender", value: "Unisex" },
    ],
  }),
  buildProduct({
    id: "e-002",
    slug: "persol-po3092v",
    title: "PO3092V",
    brand: "Persol",
    category: "eyewear",
    subtype: "frame",
    shortDescription: "Italian acetate frame with refined keyhole bridge.",
    description:
      "A premium frame with subtle character and enduring build quality.",
    price: 259,
    currency: "EUR",
    stockStatus: "limited",
    quantity: 2,
    featured: true,
    isNew: false,
    status: "active",
    primaryCtaMode: "add_to_cart",
    imageAlt: "Persol acetate frame with amber finish",
    specs: [
      { key: "frame_type", value: "Frames" },
      { key: "shape", value: "Round" },
      { key: "material", value: "Acetate" },
      { key: "color", value: "Havana" },
      { key: "gender", value: "Unisex" },
    ],
  }),
  buildProduct({
    id: "e-003",
    slug: "oakley-holbrook",
    title: "Holbrook",
    brand: "Oakley",
    category: "eyewear",
    subtype: "sunglasses",
    shortDescription: "Durable performance-inspired sunglasses with clean lines.",
    description:
      "Strong daily sunglasses profile with lightweight comfort and lens clarity.",
    price: 189,
    currency: "EUR",
    stockStatus: "in_stock",
    quantity: 6,
    featured: true,
    isNew: false,
    status: "active",
    primaryCtaMode: "add_to_cart",
    imageAlt: "Oakley Holbrook sunglasses in matte black",
    specs: [
      { key: "frame_type", value: "Sunglasses" },
      { key: "shape", value: "Square" },
      { key: "material", value: "Injected" },
      { key: "color", value: "Matte Black" },
      { key: "gender", value: "Unisex" },
    ],
  }),
  buildProduct({
    id: "e-004",
    slug: "vogue-vo5230",
    title: "VO5230",
    brand: "Vogue",
    category: "eyewear",
    subtype: "frame",
    shortDescription: "Elegant cat-eye optical frame for everyday styling.",
    description:
      "A balanced feminine silhouette with comfortable fit and refined detailing.",
    price: 119,
    currency: "EUR",
    stockStatus: "in_stock",
    quantity: 5,
    featured: false,
    isNew: true,
    status: "active",
    primaryCtaMode: "add_to_cart",
    imageAlt: "Vogue cat-eye frame in walnut tone",
    specs: [
      { key: "frame_type", value: "Frames" },
      { key: "shape", value: "Cat Eye" },
      { key: "material", value: "Acetate" },
      { key: "color", value: "Brown" },
      { key: "gender", value: "Women" },
    ],
  }),
  buildProduct({
    id: "e-005",
    slug: "tom-ford-ft5694",
    title: "FT5694",
    brand: "Tom Ford",
    category: "eyewear",
    subtype: "frame",
    shortDescription: "Premium acetate frame with signature bridge line.",
    description:
      "A high-end optical frame with clean architectural shaping and strong finish.",
    price: 349,
    currency: "EUR",
    stockStatus: "available_on_request",
    quantity: null,
    featured: true,
    isNew: false,
    status: "active",
    primaryCtaMode: "whatsapp_inquiry",
    imageAlt: "Tom Ford premium frame product image",
    specs: [
      { key: "frame_type", value: "Frames" },
      { key: "shape", value: "Rectangular" },
      { key: "material", value: "Acetate" },
      { key: "color", value: "Black" },
      { key: "gender", value: "Unisex" },
    ],
  }),
  buildProduct({
    id: "e-006",
    slug: "polaroid-pld-4065s",
    title: "PLD 4065/S",
    brand: "Polaroid",
    category: "eyewear",
    subtype: "sunglasses",
    shortDescription: "Polarized sunglasses with practical lightweight frame.",
    description:
      "An easy-wear sunglasses option with dependable polarized lens performance.",
    price: 89,
    currency: "EUR",
    stockStatus: "in_stock",
    quantity: 10,
    featured: false,
    isNew: false,
    status: "active",
    primaryCtaMode: "add_to_cart",
    imageAlt: "Polaroid sunglasses with dark lenses",
    specs: [
      { key: "frame_type", value: "Sunglasses" },
      { key: "shape", value: "Round" },
      { key: "material", value: "Metal" },
      { key: "color", value: "Gold" },
      { key: "gender", value: "Unisex" },
    ],
  }),
  buildProduct({
    id: "e-007",
    slug: "emporio-armani-ea1105",
    title: "EA1105",
    brand: "Emporio Armani",
    category: "eyewear",
    subtype: "frame",
    shortDescription: "Slim metal frame with contemporary understated look.",
    description:
      "A precise frame profile suitable for business and everyday wear.",
    price: 149,
    currency: "EUR",
    stockStatus: "limited",
    quantity: 1,
    featured: false,
    isNew: false,
    status: "active",
    primaryCtaMode: "add_to_cart",
    imageAlt: "Emporio Armani optical frame closeup",
    specs: [
      { key: "frame_type", value: "Frames" },
      { key: "shape", value: "Rectangular" },
      { key: "material", value: "Metal" },
      { key: "color", value: "Gunmetal" },
      { key: "gender", value: "Men" },
    ],
  }),
  buildProduct({
    id: "e-008",
    slug: "guess-gu00123",
    title: "GU00123",
    brand: "Guess",
    category: "eyewear",
    subtype: "sunglasses",
    shortDescription: "Fashion-forward sunglasses with soft geometric lines.",
    description:
      "A character-led sunglasses profile designed for expressive daily styling.",
    price: 109,
    currency: "EUR",
    stockStatus: "in_stock",
    quantity: 9,
    featured: true,
    isNew: true,
    status: "active",
    primaryCtaMode: "add_to_cart",
    imageAlt: "Guess sunglasses angled product shot",
    specs: [
      { key: "frame_type", value: "Sunglasses" },
      { key: "shape", value: "Geometric" },
      { key: "material", value: "Injected" },
      { key: "color", value: "Tortoise" },
      { key: "gender", value: "Women" },
    ],
  }),
];
